require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - 'test_prof/rubocop'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - node_modules/**/*
    - bin/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false
