require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - 'test_prof/rubocop'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/MethodLength:
  Max: 50

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Enabled: false
